### ISSUE TITLE
[How to use karma]

### ISSUE THREAD

**Issue by ghost** [eddyerburgh/how-to-unit-test-vue-components-for-beginners#1]
Hello,

I tried many Vue.JS test and you are the one which is working, thank you !

I followed your tutorial but I want to make it using karma.conf.js and jasmine, do you know how to do that?

Thank you

**Comment by eddyerburgh** [comment]
Hi @benjaminbatista ,

There is a repo here that uses karma and webpack - https://github.com/eddyerburgh/avoriaz-karma-mocha-example

I imagine using jasmine would be a case of switching 'mocha', in this array - https://github.com/eddyerburgh/avoriaz-karma-mocha-example/blob/master/test/unit/karma.conf.js#L45 and running ```npm install --save-dev karma-mocha```

If you have troubles setting it up, I'll look into making an example repo either tonight or tomorrow, and will send you a link 😄

**Comment by ghost** [comment]
Wow thank you so much for your quick reply ! 👍 

I'll see your repo with karma.

Ok thank you @eddyerburgh !

**Comment by eddyerburgh** [comment]
Hi @benjaminbatista ,

I've made an example repo using karma and jasmine - https://github.com/eddyerburgh/avoriaz-karma-jasmine-example

**Comment by ghost** [comment]
Oh that's so nice of you !
Thank you so much, that will really help us

**Comment by ghost** [comment]
I have one more question, is it possible to test a component that is created thanks to "Vue.component('blablalba')" and not inside a .Vue file?

**Comment by eddyerburgh** [comment]
@benjaminbatista try calling Vue.component('Component'), then call avoriaz.mount(Component)

If it doesn't work, start an issue on avoriaz - https://github.com/eddyerburgh/avoriaz/issues/new

**Comment by ghost** [comment]
I'll try to explain better:
This is the project github repo; https://github.com/Viseo/C360/blob/develop/src/main/webapp/app/controller/registerTrainingTopic.js

We are trying to test the three component of registerTrainingTopic.js 

My karma config is here: https://github.com/Viseo/C360/blob/develop/karma.conf.js

And I'm currently trying to use it with avoriaz or something else but I don't know how to retrieve the component in a spec.js test file.

Thank you eddy :)

**Comment by eddyerburgh** [comment]
Wow, that's a big component.

Have you tried just calling Vue.component() with a mock?
